#!/usr/bin/python

import psutil
#How wide to make the bar (default is 20)
totalBlocks=20

barColor="#6190bd"
bgColor="#ebbab9"
barChar="█"
bgChar="█" 
#barChar="|"
#bgChar="|"
blockPercent=100/totalBlocks

CPU_Util=psutil.cpu_percent(interval=9)

numBlocks=round(CPU_Util/blockPercent)

CPU_Block= barChar * numBlocks

CPU_Block_J = bgChar * (totalBlocks-numBlocks)

print("<span color=\"" + barColor + "\">" + CPU_Block + "</span>" + "<span color=\"" + bgColor + "\">" + CPU_Block_J + "</span>")
print(CPU_Block_J)

