#!/usr/bin/python

import psutil

CPU_Util=psutil.cpu_percent(interval=1)
CPU_String=str(CPU_Util).rjust(4, '0')

print(CPU_String + '%')
print(CPU_String + '%')

if CPU_Util > 80:
    print("#FF0000")
elif CPU_Util > 50:
    print("#FFFF00")

