#!/usr/bin/python

import psutil
#How wide to make the bar (default is 20)
totalBlocks=20

barColor="#6190bd"
bgColor="#ebbab9"
barChar="█"
bgChar="█" 
#barChar="|"
#bgChar="|"
blockPercent=100/totalBlocks

RAM_Util=psutil.virtual_memory().percent

numBlocks=round(RAM_Util/blockPercent)

RAM_Block= barChar * numBlocks

RAM_Block_J = bgChar * (totalBlocks-numBlocks)

print("<span color=\"" + barColor + "\">" + RAM_Block + "</span>" + "<span color=\"" + bgColor + "\">" + RAM_Block_J + "</span>")
print(RAM_Block_J)
